### ISSUE TITLE
Create automated test for POST /

### ISSUE THREAD

**Issue by levino** [tmnrkb/Web3-Express-NodeJS-TypeScript#1]
Please create a test for a `POST` to the root. I am not willing to checkout this repo, start the app and then use postman to post something to the endpoint. I am however willing to checkout the repo and run `npm test` to reproduce your problem.

[Context](https://github.com/ethereum/web3.js/issues/1658#issuecomment-398639013)

**Comment by levino** [comment]
As a hint: [supertest](https://www.npmjs.com/package/supertest) is very nice for this.

**Comment by tomo1026j** [comment]
Thanks for your information.
I created simple test code.
