### ISSUE TITLE
Use new

### ISSUE THREAD

**Issue by levino** [tmnrkb/Web3-Express-NodeJS-TypeScript#2]
Why are you doing this? 

https://github.com/tomo1026j/SampleWeb3/blob/5bd9a32c7ca1d915c80417f7841bcde468626f40/src/index.ts#L14-L15

I would say it should rather be
```ts
const web3 = new Web3('http://localhost:8485')
```

**Comment by tomo1026j** [comment]
Oh! Thanks, it's working!
Appreciate it!

**Comment by levino** [comment]
Did this fix your initial issue? Glad to be able to help.

**Comment by levino** [comment]
Your code does not work at all. Here you copied the wrong port from my code above
https://github.com/tomo1026j/SampleWeb3/blob/c750d70798b67f164683e8854a187932b64d674c/src/index.ts#L19
It needs to be `8545`.
And here you are basically throwing a function into the `res.send` function
https://github.com/tomo1026j/SampleWeb3/blob/c750d70798b67f164683e8854a187932b64d674c/src/index.ts#L22
Again: You are sending a function back, not the result of a call to that function. Even if you would call that function you would have to wait for the result before you could give it to `res.send` because it is an async function that returns a promise.
